### ISSUE TITLE
All WinUI 3 / WASDK api reference docs are missing / broken

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winui-api#119]
As per the title, try visiting various api docs:

https://docs.microsoft.com/en-us/windows/winui/api/

Selecting WinUI 3 from the left drop down doesn't work. 

Trying to open WinUI 3 doc links from Visual Studio always fails.

![Screenshot 2022-05-28 110050](https://user-images.githubusercontent.com/5379488/170830984-729eeb15-0f40-4173-82b0-fdadf1766454.jpg)

**Comment by asklar** [comment]
@GrantMeStrength @stevewhims fyi

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @kmgallahan - actively working on this. Some of this should be sorting itself out as related PRs are merged and search engines update.

**Comment by MarkBrainfire** [comment]
Wow!  The ENTIRE DOCUMENTATION FOR WINUI 3 IS BROKEN and no one is fixing this?  I raised this issue a week ago.  Who sets the priorities here?  WinUI 3 is the future for Windows and cross platform development (via UNO and MAUI) and yet Microsoft tolerates an entire week going by where no one can access any documentation?

It's funny ... my mental model is that Microsoft employs large teams working on its key technologies.  In my mind, WinUI 3 is kind of a big deal.  Am I wrong?  Are there just a couple of people working on it?  When someone breaks the entire online documentation for Microsoft's MAIN FUTURE TECHNOLOGY is no one held responsible?  

I'm basing my entire future on WinUI 3.  Am I wrong to do so?  Is Microsoft running things this casually?  

Hello?????

**Comment by kmgallahan** [comment]
@MarkBrainfire It appears that everything was moved [here](https://docs.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml?view=windows-app-sdk-1.0), but the migration wasn't handled very well (and probably isn't complete regarding all references & links).

**Comment by marb2000** [comment]
Thank you @kmgallahan  and @MarkBrainfire for reporting this. Our doc team is working on fixing the broken links. We did massive changes and we are trying to fix them ASAP. 
Also, apologies for these issues.

**Comment by MarkBrainfire** [comment]
@marb2000 THANK YOU!  "Massive changes" sounds intriguing.  Great knowing that you're working on this.  No apologies needed.  I remain enthusiastic about the potential of C# and WinUI 3.

**Comment by michael-hawker** [comment]
@marb2000 is there an ETA for this? Is there a reason this has the `Pri3` label? That seems incorrect?

The WinUI 2 docs used to be easily switched to the WinUI 3 ones to look up/compare. But now the link just lands you on the WinAppSDK landing page which isn't helpful.

**Comment by kmgallahan** [comment]
@michael-hawker `Pri3` appears to be applied to any issue not created through the Docs Feedback mechanism.

I also don't think the API docs should reference and cross-link to each other since the WinUI 2 vs 3 naming is not optimal (they aren't really version numbers of the same product). 

The naming "WinUI for UWP" and "WinUI for WASDK" is less confusing, and appears to now be present on the WinUI 2 pages:

> This documentation applies to WinUI 2 for UWP (for [WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/) in the [Windows App SDK](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/), see the [Windows App SDK namespaces](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/)).

While the WinUI for WASDK pages don't link back to WinUI 2 - which I like as development of it and UWP are basically dead at this point, so no need to confuse newcomers.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @kmgallahan, @MarkBrainfire, @michael-hawker - There were a lot of moving parts to this restructuring and because of much duplication of APIs between UWP, WinUI2, WinUI in the Windows App SDK, global search and replaces were problematic and had the potential to introduce many more issues that would be difficult to recover cleanly from. I decided to err on the side of caution and make the link updates as solid as possible. Our build tools were also an issue over the last week or so, which slowed things down a bit. 

I think this particular issue has been resolved (the version drop down showing WinUI 3 and redirecting to WinUI 2 topics). The cross links from across related doc repos have also been addressed for the most part. However, I expect there might still be some glitches here and there that I hope our broken link reports will help me identify and fix over time.

If you still encounter cross link or redirection problems, please open a new Issue and I'll try to address ASAP.

**Comment by michael-hawker** [comment]
@Karl-Bridge-Microsoft I agree this issue that was more geared towards the drop-down is resolved. But I still see issues overall with how things are linked together. Would you like me to open a new issue to explain? `NavigationView` is a great example for this.

> I also don't think the API docs should reference and cross-link to each other since the WinUI 2 vs 3 naming is not optimal (they aren't really version numbers of the same product).
> 
> The naming "WinUI for UWP" and "WinUI for WASDK" is less confusing, and appears to now be present on the WinUI 2 pages:
> 
> > This documentation applies to WinUI 2 for UWP (for [WinUI](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/) in the [Windows App SDK](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/), see the [Windows App SDK namespaces](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/)).
> 
> While the WinUI for WASDK pages don't link back to WinUI 2 - which I like as development of it and UWP are basically dead at this point, so no need to confuse newcomers.

@kmgallahan I can get behind having the WinAppSDK control pages not linking backwards, but having the UWP ones point to WinUI 2, and the WinUI 2 ones point to WinAppSDK is really helpful. As a library author or someone needing to port a UWP application to the WinAppSDK, there can be differences in the APIs between them sometimes, so being able to quickly go from my current doc set to the new version of it without having to do yet another search is important. This flow worked rather well in the old setup.

**Comment by Karl-Bridge-Microsoft** [comment]
@michael-hawker - A new Issue would be better for tracking. Thanks!
